### ISSUE TITLE
Strange visual artifacts on OSX

### ISSUE THREAD

**Issue by Sam-Cleveland** [AnonymouX47/term-image#53]
Hey, I just installed term-image on OSX and upon trying multiple images, I seem to get visual artifacts upon loading images (especially those with transparent backgrounds). I have tried a couple different images (in both png and jpeg format) and the issue seems to persist. It's possible that this is some user error but I haven't done anything besides install it and use it right off the bat. I'll include the images along with this issue to see if others can get these to render.

**Steps to reproduce the behavior:**

1. Install term-image via zsh Terminal (pip3 install term-image)
2. Open image (term-image ~/Downloads/image.png)

**Screenshots**
<img width="477" alt="Screen Shot 2022-06-17 at 3 27 14 PM" src="https://user-images.githubusercontent.com/104586689/174408676-1bd1f16f-cfa6-4bed-af52-f0af6a780f62.png">

**Desktop (please complete the following information, if applicable):**

- OSX 12.2.1
- Most Recent term-image
- zsh terminal

**Package info:**

- Python version: 3.9.13
- pip: 22.0.3

Original images used:
![image](https://user-images.githubusercontent.com/104586689/174408729-f853711a-337c-4dc8-98ad-c69493cd4279.jpeg)
![image](https://user-images.githubusercontent.com/104586689/174408739-5839c92e-c78d-43d3-801f-7822ad9f20cf.png)

**Comment by AnonymouX47** [comment]
Thanks for reporting :smiley:

> zsh terminal

`zsh` is a shell, not a terminal emulator.  Examples of a terminal emulator are the MacOS **Terminal**, iTerm2, etc.

From what I can see in the output, it's seems the terminal emulator doesn't have proper truecolor support.
Please, let me know exactly which terminal emulator you used here and we can figure things out from there.

N.B: I do not have immediate access to a Mac. So, even if I knew the terminal emulator, probing the issue might take a while on my end.
Also, I tested on iTerm2 not too long ago and it worked just fine. So, I'm assuming this is not iTerm2.

**Comment by AnonymouX47** [comment]
![Screenshot_2022-06-18_14-12-23](https://user-images.githubusercontent.com/61663146/174439292-10671ca2-25af-46de-9f65-d33152d15108.png)

Both images were properly displayed here on the **Kitty** terminal emulator...

**Comment by AnonymouX47** [comment]
Check the [requirements](https://github.com/AnonymouX47/term-image#requirements) and ensure the **third** one is satisfied.

**Comment by Sam-Cleveland** [comment]
> Please, let me know exactly which terminal emulator you used here and we can figure things out from there.

This was on the native OSX Terminal

> **N.B:** I do not have immediate access to a Mac. So, even if I knew the terminal emulator, probing the issue might take a while on my end. Also, I tested on iTerm2 not too long ago and it worked just fine. So, I'm assuming this is not iTerm2.

I'd be glad to assist with any testing for OSX
